/home/awaludinmastur/datasantri2018.csv
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ZAID','L','2008-12-13']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['MUHAMMAD SYAFIQ','L','2009-09-15']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ABDURRAHMAN','L','2010-06-09']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. AL QOSIM','L','2010-07-23']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. AZKA','L','2012-02-21']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ALFIN M. RIZKI','L','2011-09-16']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. AFFAN ZIKRI','L','2013-04-27']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NASHIRURRAHMAN','L','2011-07-22']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AHMAD IRSYAD','L','2009-12-04']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AGUNG','L','2003-07-30']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['DAFFA OKTARIAWAN','L','2013-10-10']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['DIVO DIFA DINATA','L','2009-05-13']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['HIDAYAT','L','2011-11-23']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['JEKI','L','2003-10-18']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['MUHAMMAD DZAKI FARUQ','L','2007-12-04']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. WALFAIZAN','L','2011-09-20']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['QOLBI SALIM','L','2009-10-01']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['YUSUF DERMAWAN','L','2008-05-20']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ZAIDI','L','2005-08-07']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ZAKARIA AKBAR','L','2009-12-03']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ABDULLAH','L','2013-11-11']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ALDI','L','2007-10-04']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SYAHRUL AZAM','L','2013-03-30']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NAUFAL SHADIQ','L','2012-05-25']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['MUHAMMAD LUQMAN HANIF','L','2013-02-24']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. RIDHO RIANZA','L','2004-11-08']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['HASYAN','L','2005-06-20']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['FIRDAUS','L','2006-05-12']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['HANIF AMRULLAH','L','2001-08-17']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SUFYAN ABDILLAH','L','2006-01-28']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AYYUB','L','2008-08-30']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['M. DZAKIRIN','L','2005-01-26']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['BASTIAN','L','2003-01-21']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AHMAD HIRA','L','2003-02-28']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ABDULLAH','L','2009-01-13']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['URAY RESTU SAPUTRA','L','2013-04-26']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AFIFAH HUMAIRA','P','2008-09-30']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AISYAH UMM NAFIAH','P','2012-07-10']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ASTRI SANDIWIA','P']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['AZIZAH','P']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['PARINI','P']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['IGFA RIANKA','P','2008-01-18']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['LIVIA','P','2009-05-11']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NAFIA MARITZA ARNI','P','2011-05-31']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NAYLA MAYAZA ARNI','P','2010-02-10']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['MUSTAGHFIROH','P','2012-06-11']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['OKTA RIANTI','P','2011-04-20']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SITI ANNISA FITRI','P','2007-08-02']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['FATHIMATTUZZAHRA','P','2006-10-09']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['ASMA' UMMU HABIBAH','P','2009-11-13']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SHAZA SHAZWINA','P','2007-04-08']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SHAFIQAH NURAINI','P','2012-06-25']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['FATHIMAH','P','2012-06-14']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['FATIMAH','P','2011-10-17']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['SITI RAHMAWATI','P','2011-07-25']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['MINARSIH','P','2004-02-03']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NUR AINI','P','2010-06-14']);
DB::table('data_santri')->insert('insert into data_santri (nama_santri, jenis_kelamin, tanggal_lahir) values (?,?,?)', ['NURI HERDIANA','P','2013-02-12']);
